In [1]:
import numpy as np

In [3]:
lst1=[1,2]
lst2=[2,3]
lst3=[3,4]

arr = np.array([lst1, lst2, lst3])

print(arr)
            

[[1 2]
 [2 3]
 [3 4]]


In [4]:
arr = np.array([1,2,3,4])

numpy.ndarray

In [9]:
lst1=[6,7]
lst2=[7,9]
lst3=[4,5]
lst4=[3,3]

arr = np.array([lst1, lst2, lst3, lst4])

print(arr)

print(type(arr))

arr.shape

[[6 7]
 [7 9]
 [4 5]
 [3 3]]
<class 'numpy.ndarray'>


(4, 2)

In [10]:
arr = np.array([1,2,3,4,5,6,7])

arr

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
arr = np.array([5,7,9,4])

print(arr[0])
print(arr[1])
print(arr[2])

5
7
9


In [20]:
arr = np.array([1, 2, 3, 4])

print(arr[1] + arr[2])



5


In [39]:
arr = np.array([[[1, 2, 3], [6, 4, 5]], [[11, 12, 13], [8, 9, 10]]])


print(arr)

[[[ 1  2  3]
  [ 6  4  5]]

 [[11 12 13]
  [ 8  9 10]]]


In [40]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [43]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)


<U6


In [47]:
arr = np.array([1, 2, 3 , 4, 5])
x = arr.copy()
arr[4]=42

print(arr)
print(x)


[ 1  2  3  4 42]
[1 2 3 4 5]


In [50]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(2,2,3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [51]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
arr[3:]=100

In [53]:
arr


array([  1,   2,   3, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [54]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])

[ 1  4  9 16 25]


In [55]:
arr1*arr2

array([ 1,  4,  9, 16, 25])

In [56]:
x = "awesome"

def myfunc():
  print("Python is " + x)

myfunc()

Python is awesome


In [60]:
x = range(6)

In [61]:
print(x)

range(0, 6)


In [62]:
x = 35e3
y = 12E4
z = -87.7e100

print(type(x))
print(type(y))
print(type(z))

<class 'float'>
<class 'float'>
<class 'float'>


In [63]:
x = 3+5j
y = 5j
z = -5j

print(type(x))
print(type(y))
print(type(z))

<class 'complex'>
<class 'complex'>
<class 'complex'>


In [64]:
x = int(1)   # x will be 1
y = int(2.8) # y will be 2
z = int("3") # z will be 3

In [65]:
print(x)
print(y)
print(z)

1
2
3


In [67]:
a = "Hello, World!"
print(a[1])


e


In [68]:
for x in "banana":
  print(x)


b
a
n
a
n
a


In [69]:
a = "Hello, World!"
print(len(a))

13


In [70]:
txt = "The best things in life are free!"
print("free" in txt)


True


In [71]:
b = "Hello, World!"
print(b[2:5])

llo


In [72]:
b = "Hello, World!"
print(b[:5])

Hello


In [73]:
b = "Hello, World!"
print(b[-5:-2])

orl


In [1]:
b = "Hello, World!"
print(b[-5:-2])

orl


In [2]:
a = "Hello, World!"
print(a.upper())

HELLO, WORLD!


In [3]:
a = "Hello, World!"
print(a.lower())

hello, world!


In [4]:
#The replace() method replaces a string with another string:

a = " Hello, World! "
print(a.strip()) # returns "Hello, World!"

Hello, World!


In [5]:
#The split() method returns a list where the text between the specified separator becomes the list items.

a = "Hello, World!"
print(a.split(",")) # returns ['Hello', ' World!']

['Hello', ' World!']


In [6]:
To concatenate, or combine, two strings you can use the + operator.

a = "Hello"
b = "World"
c = a + b
print(c)

HelloWorld


In [7]:
To add a space between them, add a " ":

a = "Hello"
b = "World"
c = a + " " + b
print(c)

Hello World


In [9]:
#We can combine strings and numbers by using the format() method!

The format() method takes the passed arguments, formats them, and places them in the string where the placeholders {} are:

Example
Use the format() method to insert numbers into strings:

age = 36
txt = "My name is John, and I am {}"
print(txt.format(age))

My name is John, and I am 36


In [10]:
quantity = 3
itemno = 567
price = 49.95
myorder = "I want {} pieces of item {} for {} dollars."
print(myorder.format(quantity, itemno, price))

I want 3 pieces of item 567 for 49.95 dollars.


In [11]:
quantity = 3
itemno = 567
price = 49.95
myorder = "I want to pay {2} dollars for {0} pieces of item {1}."
print(myorder.format(quantity, itemno, price))

I want to pay 49.95 dollars for 3 pieces of item 567.


In [13]:
txt = "We are the so-called \"Vikings\" from the north."

In [14]:
txt

'We are the so-called "Vikings" from the north.'

In [15]:
txt = "Hello\nWorld!"
print(txt) 


Hello
World!


In [16]:
txt = "Hello \bWorld!"
print(txt)

Hello World!


In [18]:
txt = "We are the so-called \"gryffindor\" from the north."
print(txt)

We are the so-called "gryffindor" from the north.


In [19]:
print(10 > 9)
print(10 == 9)
print(10 < 9)

True
False
False


In [20]:
a = 200
b = 33

if b > a:
  print("b is greater than a")
else:
  print("b is not greater than a")

b is not greater than a


In [21]:
print(bool("Hello"))
print(bool(15))

True
True


In [22]:
bool("abc")
bool(123)
bool(["apple", "cherry", "banana"])

True

In [23]:
bool(False)
bool(None)
bool(0)
bool("")
bool(())
bool([])
bool({})

False

In [24]:
x = 5

x%=3

print(x)

2


In [25]:
x = 5

x |= 3

print(x)

7


In [26]:
x = 5

x ^= 3

print(x)

6


In [27]:
x = 5

x &= 3

print(x)


1


In [28]:
x = 5

x >>= 3

print(x)

0


In [29]:
x = 5

x//=3

print(x)


1


In [30]:
x = ["apple", "banana"]

print("banana" in x)

# returns True because a sequence with the value "banana" is in the list

True


In [31]:
x = ["apple", "banana"]

print("pineapple" not in x)

# returns True because a sequence with the value "pineapple" is not in the list

True


In [32]:
x = 5

print(not(x > 3 and x < 10))

# returns False because not is used to reverse the result

False


In [34]:
#Create a List:

thislist = ["apple", "banana", "cherry"]
print(thislist)

['apple', 'banana', 'cherry']


In [35]:
thislist = ["apple", "banana", "cherry", "apple", "cherry"]
print(thislist)

['apple', 'banana', 'cherry', 'apple', 'cherry']


In [36]:
#List Length
#To determine how many items a list has, use the len() function:

#Example
#Print the number of items in the list

thislist = ["apple", "banana", "cherry"]
print(len(thislist))

3


In [37]:
#A list can contain different data types:

#Example
#A list with strings, integers and boolean values:

list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]

print(list1)
print(list2)
print(list3)


['apple', 'banana', 'cherry']
[1, 5, 7, 9, 3]
[True, False, False]


In [38]:
mylist = ["apple", "banana", "cherry"]
print(type(mylist))

<class 'list'>


In [39]:
thislist = list(("apple", "banana", "cherry")) # note the double round-brackets
print(thislist)

['apple', 'banana', 'cherry']


In [40]:
#Example
#Return the third, fourth, and fifth item:

thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[2:5])

['cherry', 'orange', 'kiwi']


In [41]:
#This example returns the items from the beginning to, but NOT including, "kiwi":

thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[:4])

['apple', 'banana', 'cherry', 'orange']


In [42]:
#This example returns the items from "orange" (-4) to, but NOT including "mango" (-1):

thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[-4:-1])

['orange', 'kiwi', 'melon']


In [43]:
thislist = ["apple", "banana", "cherry"]
if "apple" in thislist:
  print("Yes, 'apple' is in the fruits list")

Yes, 'apple' is in the fruits list


In [44]:
thislist = ["apple", "banana", "cherry"]
thislist[1] = "blackcurrant"
print(thislist)

['apple', 'blackcurrant', 'cherry']


In [45]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]
thislist[1:3] = ["blackcurrant", "watermelon"]
print(thislist)

['apple', 'blackcurrant', 'watermelon', 'orange', 'kiwi', 'mango']


In [46]:
thislist = ["apple", "banana", "cherry"]
thislist[1:3] = ["watermelon"]
print(thislist)

['apple', 'watermelon']


In [47]:
thislist = ["apple", "banana", "cherry"]
thislist.insert(2, "watermelon")
print(thislist)

['apple', 'banana', 'watermelon', 'cherry']


In [48]:
#To add an item to the end of the list, use the append() method:

thislist = ["apple", "banana", "cherry"]
thislist.append("orange")
print(thislist)

['apple', 'banana', 'cherry', 'orange']


In [49]:
#To insert a list item at a specified index, use the insert() method.

#The insert() method inserts an item at the specified index:

#Example
#Insert an item as the second position:

thislist = ["apple", "banana", "cherry"]
thislist.insert(1, "orange")
print(thislist)

['apple', 'orange', 'banana', 'cherry']


In [50]:
thislist = ["apple", "banana", "cherry"]
thislist.remove("banana")
print(thislist)

['apple', 'cherry']


In [51]:
#The pop() method removes the specified index.

#Example
#Remove the second item:

thislist = ["apple", "banana", "cherry"]
thislist.pop(1)
print(thislist)


['apple', 'cherry']


In [52]:
#If you do not specify the index, the pop() method removes the last item.

thislist = ["apple", "banana", "cherry"]
thislist.pop()
print(thislist)

['apple', 'banana']


In [53]:
#The del keyword also removes the specified index

thislist = ["apple", "banana", "cherry"]
del thislist[0]
print(thislist)

['banana', 'cherry']
